/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test void testQuotes() {  // test can read from Json file and choose a random quote
Quotes quote = Quotes.readQuotes("src/test/resources/recentquotes.json") ;
      Assertions.assertNotNull(quote);
  }
}
