/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

public class App {

    public static void main(String[] args) {
Quotes randomQuoteFromFile = new Quotes();
        Quotes a = randomQuoteFromFile.readQuotesFromFile("app/src/main/resources/recentQuotes.json");

        System.out.println("Number of quotes from file: " + randomQuoteFromFile.quotesData.size());

        Quotes quoteFromApi1 =randomQuoteFromFile.readQuotesFromApi();
        Quotes quoteFromApi2 = randomQuoteFromFile.readQuotesFromApi();


        System.out.println("Total number of quotes: " + randomQuoteFromFile.quotesData.size());
    }
}


